dist: trusty
sudo: false
notifications:
  email: false
env:
  - DB=mysql
  - DB=postgresql
addons:
  postgresql: "9.4"
  apt:
    packages:
      - autoconf
      - automake
      - autotools-dev
      - bison
      - build-essential
      - curl
      - git-core
      - libffi-dev
      - libgdbm-dev
      - libgmp-dev
      - libmysqlclient-dev
      - libncurses5-dev
      - libreadline6-dev
      - libsqlite3-dev
      - libssl-dev
      - libtool
      - libxml2-dev
      - libxslt1-dev
      - libyaml-0-2
      - libyaml-dev
      - mysql-client-5.6
      - mysql-client-core-5.6
      - mysql-server-5.6
      - patch
      - pkg-config
      - postfix
      - sqlite3
      - zlib1g-dev
services:
  - postgresql
  - mysql
language: ruby
rvm:
  - 2.4.2
before_install: contrib/travis-ci.org/before_install.sh
install: contrib/travis-ci.org/install.sh
script: contrib/travis-ci.org/script.sh
after_success: contrib/travis-ci.org/after_success.sh
